baseurl      = "https://sarel.tech/"
title        = "Sarel's Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name = "Sarel Myburgh"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  enableThemeToggle = true

  # Subtitle for home
  homeSubtitle = """
  I like cybersecurity, web development and coding. Have a look at my projects, thoughts, and CTF writeups.
  """

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Sarel Myburgh's blog"
  keywords = "homepage, blog"
  images = [""]

[params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hi, I'm Sarel"
    subtitle = "I like tech stuff"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "[sarel@blog:~$]"
      logoHomeLink = "/"
      logoCursorColor    = "#117325"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "blog/"

  [[menu.main]]
    identifier = "writeups"
    name       = "Writeups"
    url        = "writeups/"

  [[menu.main]]
    identifier = "tutorials"
    name       = "Tutorials"
    url        = "tutorials/"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"

  #Social Icons

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/jmsarel/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sarelmyburgh"

  [[params.social]]
    name = "tryhackme"
    url  = "https://tryhackme.com/p/PSyCHoH4x0r"